## Numpy Prectise material

In [98]:
import numpy as np

### Numpy array creation method

In [3]:
lst = list(range(1,25))
arr1 = np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [5]:
arr2 = np.arange(1,25)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [6]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,4,5,6,1,2,3])
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 1, 2, 3])

In [9]:
arr4 = np.zeros((5,10))
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr5 = np.ones((10,5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
arr6 = np.linspace(1,10,5)
arr6
# 1 to  6,   5 elements

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
arr7 = np.arange(0,30).reshape(10,3)
arr7

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

### random initialliazation array creation method

In [12]:
arr_1_D = np.random.randint(1,5,9)
arr_1_D

array([4, 3, 4, 1, 4, 4, 1, 1, 1])

In [15]:
arr_2_D = np.random.random((5,10))
arr_2_D

array([[0.56125422, 0.39243805, 0.70555173, 0.71317838, 0.28943659,
        0.71389519, 0.23745193, 0.44739631, 0.624878  , 0.3086042 ],
       [0.15477167, 0.8491195 , 0.47232781, 0.40792026, 0.1229388 ,
        0.51769186, 0.40642161, 0.83237417, 0.59620608, 0.73092107],
       [0.15259493, 0.49865868, 0.30468957, 0.45275084, 0.38578069,
        0.18225771, 0.41251402, 0.19171861, 0.38269774, 0.681346  ],
       [0.96052502, 0.54125768, 0.44884614, 0.25420142, 0.80533847,
        0.76057546, 0.91448951, 0.6728468 , 0.16691025, 0.08867564],
       [0.31638983, 0.32055368, 0.63856086, 0.77907571, 0.26675734,
        0.11025743, 0.72484816, 0.69993759, 0.24032205, 0.74300028]])

### Array attribute

In [26]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
arr.shape

(12, 5)

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr.ndim

2

In [31]:
arr.size     # total no. of elements

60

In [32]:
arr.flatten()    # converting in 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [33]:
arr.ravel()       # converting 1 D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [37]:
list_2D = [[1,2,3],[4,5,6]]
list_2D

[[1, 2, 3], [4, 5, 6]]

In [39]:
arr = np.array(list_2D)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr.shape

(2, 3)

In [44]:
arr.T.shape         ## transposing the shape of the data

(3, 2)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Acessing elements from array 1D and 2D array

In [99]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [52]:
arr[1]   # particular row

array([5, 6, 7, 8, 9])

In [53]:
arr[1,1]    # row and particular element define with column

6

In [60]:
arr[1,3:5]

array([8, 9])

In [73]:
arr[7:8,4][0]=100

In [74]:
arr
# 22 manupualating by 500

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

### accessing 59 from last by multiple way 

In [103]:
arr[11][-1]

59

In [107]:
arr[11:,-1][0]

59

In [108]:
arr[11,4]

59

In [114]:
arr[:,4][11]

59

In [77]:
arr[4,2] = 500

In [79]:
arr[4,2]

500

In [89]:
arr[10:,3:][1,1]

59

In [90]:
arr[10:,3:][1,1] = 500

In [91]:
arr[10:,3:][1,1]

500

In [92]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 500,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 500]])

## accessing elements from 3D Array

In [115]:
arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [101]:
arr.shape

(5, 15, 3)

In [98]:
arr.ndim

3

In [105]:
arr[0][2:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [117]:
arr[:,0,:]  # fetched first row from all the tables

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [120]:
arr[:,0:1,0:1]       # only first element from all the tables

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

## replacing 100 to the 500

In [125]:
arr[2][3][1]

100

In [131]:
arr[2,3,1]

100

In [130]:
arr[2:3,3:4,1:2]

array([[[100]]])

In [129]:
arr[2:3,3:4,1:2][0][0][0]

100

# Arithmatical operation using Numpy array


In [142]:
a = [1,2,3,4,5,6,7,8,9]
b = [5,4,8,7,9,6,2,3,5]
ar1 = np.array(a)
ar2 = np.array(b)

### direct operation on element

In [134]:
ar1 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
ar1 *2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
ar1 - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
ar1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [146]:
ar1 + ar2

array([ 6,  6, 11, 11, 14, 12,  9, 11, 14])

In [ ]:
## concate

In [148]:
np.concatenate([ar1,ar2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 4, 8, 7, 9, 6, 2, 3, 5])

# python

In [8]:
tp = (1,2,3,4,5,6)

In [10]:
tp2 = (85,12)

In [13]:
tp3 = tp+tp2

In [20]:
tp.index(3)

2

In [12]:
tp

(1, 2, 3, 4, 5, 6)

In [7]:
type(a)

tuple

In [21]:
lst = list(range(1,10))

In [22]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
lst[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [29]:
lst[-1:-5:-1]

[9, 8, 7, 6]

In [32]:
lst[-5:-7:-1]

[5, 4]

In [34]:
lst * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
tp = (2,5)

In [38]:
a,b = tp

In [39]:

a

2

In [41]:
tp

(2, 5)

In [95]:
b = {2,5,8,4,6,'a',True , 8.2,9,9,(5,6)}

In [96]:
b

{(5, 6), 2, 4, 5, 6, 8, 8.2, 9, True, 'a'}

In [73]:

type(b)

set

In [63]:
b.add(10)

In [64]:
b

{2, 4, 5, 6, 8, 9, 10}

In [65]:
b.remove(10)

In [69]:

b.discard(10)

In [70]:
p = (1,'a',5.2,True)

In [71]:
p

(1, 'a', 5.2, True)